name: UgsSyncCmf
variables:
    P4_CLIENTS_ROOT_DIRECTORY: 'D:/projects'
script:
  embeddedFiles:
  - name: UgsSync
    filename: UgsSync.bat
    type: TEXT
    data: |
      cd /d %P4_CLIENTS_ROOT_DIRECTORY%
      ugs switch {{Param.PerforceStreamPath}}
      ugs init {{Param.PerforceStreamPath}} -client=%USERNAME%_%COMPUTERNAME%_{{Param.ProjectName}} -project={{Param.ProjectRelativePath}}
      set "WorkspaceFolderName={{Param.PerforceStreamPath}}"
      set "WorkspaceFolderName=%WorkspaceFolderName:/=+%"
      cd /d %P4_CLIENTS_ROOT_DIRECTORY%\%WorkspaceFolderName%
      ugs sync change={{Param.PerforceChangelistNumber}} -binaries -nogpf
      setx P4_CLIENT_DIRECTORY %P4_CLIENTS_ROOT_DIRECTORY%\%WorkspaceFolderName%
  actions:
    onEnter:
      command: '{{Env.File.UgsSync}}'
      cancelation:
        mode: NOTIFY_THEN_TERMINATE