name: UgsSyncCmf
variables:
    P4_CLIENTS_ROOT_DIRECTORY: 'D:\projects'
script:
  embeddedFiles:
  - name: UgsSync
    filename: UgsSync.bat
    type: TEXT
    data: |
      :: Go to the directory where all workspaces live
      set "WorkspaceDir=%P4_CLIENTS_ROOT_DIRECTORY%\%USERNAME%_%COMPUTERNAME%_{{Param.ProjectName}}"
      mkdir %WorkspaceDir%
      cd /d %WorkspaceDir%
      
      :: Get or Create P4 workspace with UGS
      ugs switch {{Param.PerforceStreamPath}}
      ugs init {{Param.PerforceStreamPath}} -client=%USERNAME%_%COMPUTERNAME%_{{Param.ProjectName}} -project={{Param.ProjectRelativePath}}
      
      :: Find workspace root folder named as Stream path with "/" replaced by "+" (UGS CLI does it by default)
      set "WorkspaceFolderName={{Param.PerforceStreamPath}}"
      set "WorkspaceFolderName=%WorkspaceFolderName:/=+%"
      
      :: Go to this directory
      cd /d %WorkspaceFolderName%
      
      :: @echo off
      :: Sync given changes without generating project files and redirect output to the file
      :: echo Executing ugs sync {{Param.PerforceChangelistNumber}} -nogpf ...
      :: ugs sync {{Param.PerforceChangelistNumber}} -nogpf > output.log 2>&1
      ugs sync {{Param.PerforceChangelistNumber}} -nogpf -binaries
      
      :: Search the output for the error string
      :: findstr /i "Aborted sync due to errors" output.log >nul
      :: findstr set errorlevel to 0 if string was found
      :: set error_found=%errorlevel%
      
      :: Print output to stdout and delete file
      :: type output.log
      :: del output.log
      
      :: If string was found, exiting
      :: if %error_found% equ 0 (
      ::     echo Error detected while syncing the changes. Exiting...
      ::     exit /b 1
      :: )
      echo Sync completed successfuly
      
      :: Store this path to Env variable for future using while launching the Unreal Editor and Project within
      setx P4_CLIENT_DIRECTORY %CD%
  - name: RemovePerforceWorkspace
    filename: RemovePerforceWorkspace.bat
    type: TEXT
    data: |
      :: Remove env variable
      setx P4_CLIENT_DIRECTORY ""
  actions:
    onEnter:
      command: '{{Env.File.UgsSync}}'
      cancelation:
        mode: NOTIFY_THEN_TERMINATE
    onExit:
      command: '{{Env.File.RemovePerforceWorkspace}}'
      cancelation:
        mode: NOTIFY_THEN_TERMINATE