name: UgsSyncCmf
variables:
    P4_CLIENTS_ROOT_DIRECTORY: 'D:/projects'
script:
  embeddedFiles:
  - name: UgsSync
    filename: UgsSync.bat
    type: TEXT
    data: |
      :: Go to the directory where all workspaces live
      cd /d %P4_CLIENTS_ROOT_DIRECTORY%
      
      :: Get or Create P4 workspace with UGS
      ugs switch {{Param.PerforceStreamPath}}
      ugs init {{Param.PerforceStreamPath}} -client=%USERNAME%_%COMPUTERNAME%_{{Param.ProjectName}} -project={{Param.ProjectRelativePath}}
      
      :: Find workspace root folder named as Stream path with "/" replaced by "+" (UGS CLI does it by default)
      set "WorkspaceFolderName={{Param.PerforceStreamPath}}"
      set "WorkspaceFolderName=%WorkspaceFolderName:/=+%"
      
      :: Go to this directory
      :: Sync given changes without generating project files
      :: Store this path to Env variable for future using while launching the Unreal Editor and Project within
      cd /d %P4_CLIENTS_ROOT_DIRECTORY%\%WorkspaceFolderName%
      ugs sync {{Param.PerforceChangelistNumber}} -nogpf
      setx P4_CLIENT_DIRECTORY %CD%
  actions:
    onEnter:
      command: '{{Env.File.UgsSync}}'
      cancelation:
        mode: NOTIFY_THEN_TERMINATE