name: UgsSyncSmf
script:
  embeddedFiles:
  - name: UgsSync
    filename: UgsSync.bat
    type: TEXT
    data: |
      ugs switch {{Param.PerforceStreamPath}}
      ugs init {{Param.PerforceStreamPath}} -client=%USERNAME%_%COMPUTERNAME%_{{Param.ProjectName}} -project={{Param.ProjectRelativePath}}
      set "WorkspaceFolderName={{Param.PerforceStreamPath}}"
      set "WorkspaceFolderName=%WorkspaceFolderName:/=+%"
      cd /d %WorkspaceFolderName%
      ugs sync {{Param.PerforceChangelistNumber}} -binaries -nogpf
      setx P4_CLIENT_DIRECTORY %CD%
  actions:
    onEnter:
      command: '{{Env.File.UgsSync}}'
      cancelation:
        mode: NOTIFY_THEN_TERMINATE
# TODO what the ugs variant for p4 sync /...#0
#    onExit:
#      command: unreal-engine-openjd
#      args:
#      - daemon
#      - stop
#      - --connection-file
#      - '{{Session.WorkingDirectory}}/connection.json'
#      cancelation:
#        mode: NOTIFY_THEN_TERMINATE