name: LaunchUnrealEditor
variables:
  REMOTE_EXECUTION: 'True'
script:
  embeddedFiles:
    - name: initData
      filename: init-data.yaml
      type: TEXT
      data: |
        project_path: {{Param.ProjectFilePath}}
        extra_cmd_args: {{Param.ExtraCmdArgs}}
  actions:
    onEnter:
      command: UnrealAdaptor
      args:
      - daemon
      - start
      - --connection-file
      - '{{Session.WorkingDirectory}}/connection.json'
      - --init-data
      - file://{{Env.File.initData}}
      cancelation:
        mode: NOTIFY_THEN_TERMINATE
    onExit:
      command: UnrealAdaptor
      args:
      - daemon
      - stop
      - --connection-file
      - '{{Session.WorkingDirectory}}/connection.json'
      cancelation:
        mode: NOTIFY_THEN_TERMINATE